disable-version-string: true
resolve-type-alias: false
with-expecter: true
mock-build-tags: "!compile"
inpackage: true
issue-845-fix: true
filename: "{{.InterfaceName | snakecase }}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
packages:
  github.com/ksysoev/authkeeper/pkg/core:
    interfaces:
      Repository:
      Provider:
  github.com/ksysoev/authkeeper/pkg/ui:
    interfaces:
      CoreService:
