// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package ui

import (
	context "context"

	core "github.com/ksysoev/authkeeper/pkg/core"
	mock "github.com/stretchr/testify/mock"
)

// MockCoreService is an autogenerated mock type for the CoreService type
type MockCoreService struct {
	mock.Mock
}

type MockCoreService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCoreService) EXPECT() *MockCoreService_Expecter {
	return &MockCoreService_Expecter{mock: &_m.Mock}
}

// AddClient provides a mock function with given fields: ctx, client
func (_m *MockCoreService) AddClient(ctx context.Context, client core.Client) error {
	ret := _m.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for AddClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.Client) error); ok {
		r0 = rf(ctx, client)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCoreService_AddClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddClient'
type MockCoreService_AddClient_Call struct {
	*mock.Call
}

// AddClient is a helper method to define mock.On call
//   - ctx context.Context
//   - client core.Client
func (_e *MockCoreService_Expecter) AddClient(ctx interface{}, client interface{}) *MockCoreService_AddClient_Call {
	return &MockCoreService_AddClient_Call{Call: _e.mock.On("AddClient", ctx, client)}
}

func (_c *MockCoreService_AddClient_Call) Run(run func(ctx context.Context, client core.Client)) *MockCoreService_AddClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.Client))
	})
	return _c
}

func (_c *MockCoreService_AddClient_Call) Return(_a0 error) *MockCoreService_AddClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCoreService_AddClient_Call) RunAndReturn(run func(context.Context, core.Client) error) *MockCoreService_AddClient_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClient provides a mock function with given fields: ctx, name
func (_m *MockCoreService) DeleteClient(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCoreService_DeleteClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClient'
type MockCoreService_DeleteClient_Call struct {
	*mock.Call
}

// DeleteClient is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCoreService_Expecter) DeleteClient(ctx interface{}, name interface{}) *MockCoreService_DeleteClient_Call {
	return &MockCoreService_DeleteClient_Call{Call: _e.mock.On("DeleteClient", ctx, name)}
}

func (_c *MockCoreService_DeleteClient_Call) Run(run func(ctx context.Context, name string)) *MockCoreService_DeleteClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCoreService_DeleteClient_Call) Return(_a0 error) *MockCoreService_DeleteClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCoreService_DeleteClient_Call) RunAndReturn(run func(context.Context, string) error) *MockCoreService_DeleteClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllClients provides a mock function with given fields: ctx
func (_m *MockCoreService) GetAllClients(ctx context.Context) ([]core.Client, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllClients")
	}

	var r0 []core.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]core.Client, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []core.Client); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCoreService_GetAllClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllClients'
type MockCoreService_GetAllClients_Call struct {
	*mock.Call
}

// GetAllClients is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCoreService_Expecter) GetAllClients(ctx interface{}) *MockCoreService_GetAllClients_Call {
	return &MockCoreService_GetAllClients_Call{Call: _e.mock.On("GetAllClients", ctx)}
}

func (_c *MockCoreService_GetAllClients_Call) Run(run func(ctx context.Context)) *MockCoreService_GetAllClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCoreService_GetAllClients_Call) Return(_a0 []core.Client, _a1 error) *MockCoreService_GetAllClients_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCoreService_GetAllClients_Call) RunAndReturn(run func(context.Context) ([]core.Client, error)) *MockCoreService_GetAllClients_Call {
	_c.Call.Return(run)
	return _c
}

// GetClient provides a mock function with given fields: ctx, name
func (_m *MockCoreService) GetClient(ctx context.Context, name string) (*core.Client, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 *core.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*core.Client, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *core.Client); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCoreService_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type MockCoreService_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCoreService_Expecter) GetClient(ctx interface{}, name interface{}) *MockCoreService_GetClient_Call {
	return &MockCoreService_GetClient_Call{Call: _e.mock.On("GetClient", ctx, name)}
}

func (_c *MockCoreService_GetClient_Call) Run(run func(ctx context.Context, name string)) *MockCoreService_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCoreService_GetClient_Call) Return(_a0 *core.Client, _a1 error) *MockCoreService_GetClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCoreService_GetClient_Call) RunAndReturn(run func(context.Context, string) (*core.Client, error)) *MockCoreService_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// IsRepositoryInitialized provides a mock function with no fields
func (_m *MockCoreService) IsRepositoryInitialized() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRepositoryInitialized")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockCoreService_IsRepositoryInitialized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRepositoryInitialized'
type MockCoreService_IsRepositoryInitialized_Call struct {
	*mock.Call
}

// IsRepositoryInitialized is a helper method to define mock.On call
func (_e *MockCoreService_Expecter) IsRepositoryInitialized() *MockCoreService_IsRepositoryInitialized_Call {
	return &MockCoreService_IsRepositoryInitialized_Call{Call: _e.mock.On("IsRepositoryInitialized")}
}

func (_c *MockCoreService_IsRepositoryInitialized_Call) Run(run func()) *MockCoreService_IsRepositoryInitialized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCoreService_IsRepositoryInitialized_Call) Return(_a0 bool) *MockCoreService_IsRepositoryInitialized_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCoreService_IsRepositoryInitialized_Call) RunAndReturn(run func() bool) *MockCoreService_IsRepositoryInitialized_Call {
	_c.Call.Return(run)
	return _c
}

// IssueToken provides a mock function with given fields: ctx, clientName
func (_m *MockCoreService) IssueToken(ctx context.Context, clientName string) (*core.Token, error) {
	ret := _m.Called(ctx, clientName)

	if len(ret) == 0 {
		panic("no return value specified for IssueToken")
	}

	var r0 *core.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*core.Token, error)); ok {
		return rf(ctx, clientName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *core.Token); ok {
		r0 = rf(ctx, clientName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clientName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCoreService_IssueToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueToken'
type MockCoreService_IssueToken_Call struct {
	*mock.Call
}

// IssueToken is a helper method to define mock.On call
//   - ctx context.Context
//   - clientName string
func (_e *MockCoreService_Expecter) IssueToken(ctx interface{}, clientName interface{}) *MockCoreService_IssueToken_Call {
	return &MockCoreService_IssueToken_Call{Call: _e.mock.On("IssueToken", ctx, clientName)}
}

func (_c *MockCoreService_IssueToken_Call) Run(run func(ctx context.Context, clientName string)) *MockCoreService_IssueToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCoreService_IssueToken_Call) Return(_a0 *core.Token, _a1 error) *MockCoreService_IssueToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCoreService_IssueToken_Call) RunAndReturn(run func(context.Context, string) (*core.Token, error)) *MockCoreService_IssueToken_Call {
	_c.Call.Return(run)
	return _c
}

// ListClients provides a mock function with given fields: ctx
func (_m *MockCoreService) ListClients(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListClients")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCoreService_ListClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClients'
type MockCoreService_ListClients_Call struct {
	*mock.Call
}

// ListClients is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCoreService_Expecter) ListClients(ctx interface{}) *MockCoreService_ListClients_Call {
	return &MockCoreService_ListClients_Call{Call: _e.mock.On("ListClients", ctx)}
}

func (_c *MockCoreService_ListClients_Call) Run(run func(ctx context.Context)) *MockCoreService_ListClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCoreService_ListClients_Call) Return(_a0 []string, _a1 error) *MockCoreService_ListClients_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCoreService_ListClients_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockCoreService_ListClients_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCoreService creates a new instance of MockCoreService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCoreService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCoreService {
	mock := &MockCoreService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
