// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package core

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// GetToken provides a mock function with given fields: ctx, client
func (_m *MockProvider) GetToken(ctx context.Context, client Client) (*Token, error) {
	ret := _m.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 *Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, Client) (*Token, error)); ok {
		return rf(ctx, client)
	}
	if rf, ok := ret.Get(0).(func(context.Context, Client) *Token); ok {
		r0 = rf(ctx, client)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, Client) error); ok {
		r1 = rf(ctx, client)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvider_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockProvider_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - client Client
func (_e *MockProvider_Expecter) GetToken(ctx interface{}, client interface{}) *MockProvider_GetToken_Call {
	return &MockProvider_GetToken_Call{Call: _e.mock.On("GetToken", ctx, client)}
}

func (_c *MockProvider_GetToken_Call) Run(run func(ctx context.Context, client Client)) *MockProvider_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(Client))
	})
	return _c
}

func (_c *MockProvider_GetToken_Call) Return(_a0 *Token, _a1 error) *MockProvider_GetToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvider_GetToken_Call) RunAndReturn(run func(context.Context, Client) (*Token, error)) *MockProvider_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
